import { chromium } from "playwright-core";
const exe = process.env.HOME + "/.cache/ms-playwright/chromium_headless_shell-1234/chrome-headless-shell-linux64/chrome-headless-shell";
const browser = await chromium.launch({ executablePath: exe, headless: true });
const page = await browser.newPage({ viewport: { width: 1600, height: 1000 } });
await page.goto("file:///home/z/vibe/raid_calc/raid-calc.html", { waitUntil: "commit" });
await page.waitForTimeout(1200);
const disk = page.locator('.node').filter({ hasText: 'DISK' }).first();
await disk.click();
await page.waitForTimeout(300);
console.log('labels before:', await page.locator('.props label').allTextContents());
console.log('values before:', await page.locator('.props input').evaluateAll(xs => xs.map(x => x.value)));
const cap = page.locator('.props input').first();
await cap.fill('10');
await cap.press('Enter');
await page.waitForTimeout(300);
console.log('after commit:', await page.locator('.props input').first().inputValue());
await page.locator('.node').filter({ hasText: 'OUTPUT' }).click();
await disk.click();
await page.waitForTimeout(300);
console.log('after reselect:', await page.locator('.props input').first().inputValue());
await browser.close();
