import { chromium } from "playwright-core";
const exe = process.env.HOME + "/.cache/ms-playwright/chromium_headless_shell-1234/chrome-headless-shell-linux64/chrome-headless-shell";
const browser = await chromium.launch({ executablePath: exe, headless: true });
const page = await browser.newPage();
const errors = [];
page.on("pageerror", (e) => errors.push("PAGEERROR: " + (e.stack || e.message).slice(0, 600)));
page.on("console", (m) => { if (m.type() === "error") errors.push("[console.error] " + m.text().slice(0, 600)); });
await page.goto("file:///tmp/bundle-only.html");
await page.waitForTimeout(1000);
console.log(JSON.stringify({ children: await page.evaluate(() => document.getElementById("app").childElementCount), errors }, null, 1));
await browser.close();
